### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by ruthannedilig** [ronisaha/wdCalendar#6]
Hi i cant change the date format of the datepicker even if I update it on the code. Here's the sample code
$("#stpartdate,#etpartdate").datepicker({
            dateFormat: 'd-m-Y',
            picker: "<button class='picker'></button>"
});

Any idea? Thanks

**Comment by ronisaha** [comment]
The _**datepicker**_ function doesn't have _**dateFormat**_ parameter. You can look into following file. if it helps.

> src\Plugins\wdCalendar_lang_US.js

**Comment by ruthannedilig** [comment]
Hello thank you for the reply. I already solved the problem. I just have another question. After dragging the event container, the time will be updated. Is there any way on how can I get the new time that was updated after dragging? I need to get it under cal_afterrequest function or is there any other way? Thank you appreciated much

**Comment by ruthannedilig** [comment]
thank you so much for your response
